"use client";

import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowUpRight, FileJson, UploadCloud } from "lucide-react";
import { AppShell } from "@/components/saas/app-shell";
import { EmptyState, Panel, SkeletonGrid, StatCard, StatusPill } from "@/components/saas/ui";
import { money, useWorkspace } from "@/components/saas/workspace";
import { formatCurrency } from "@/lib/utils";

export function DashboardSaasPage() {
  const workspace = useWorkspace();
  const summary = workspace.summary;
  const platformData = summary?.platform_wise_sale.map((item) => ({ name: item.platform, taxable: money(item.taxable_value), gst: money(item.gst), rows: item.rows })) || [];
  const stateData = summary?.state_wise_sale.map((item) => ({ name: item.state_code, taxable: money(item.taxable_value), gst: money(item.gst) })) || [];
  const warnings = workspace.transactions.filter((row) => row.validation_status === "error");

  return (
    <AppShell title="Command Center" subtitle="Live filing intelligence across marketplace imports, GST validations, GSTR-1 export readiness and reconciliation status." profile={workspace.profile} profiles={workspace.profiles} onProfileChange={(profile) => { workspace.setProfile(profile); workspace.refresh(profile); }} actions={<Link href="/marketplaces" className="inline-flex items-center gap-2 rounded-2xl bg-[#10244d] px-5 py-3 text-sm font-bold text-white shadow-xl shadow-blue-950/20"><UploadCloud className="size-4" /> Start import</Link>}>
      {workspace.loading ? <SkeletonGrid /> : (
        <div className="space-y-6">
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <StatCard label="Total taxable value" value={formatCurrency(money(summary?.total_taxable_value))} detail={`${summary?.platform_wise_sale.length || 0} active platforms`} tone="blue" />
            <StatCard label="Total GST" value={formatCurrency(money(summary?.total_gst))} detail={`IGST ${formatCurrency(money(summary?.igst))}`} tone="green" />
            <StatCard label="CGST / SGST" value={`${formatCurrency(money(summary?.cgst))} / ${formatCurrency(money(summary?.sgst))}`} detail="Intra-state split" tone="saffron" />
            <StatCard label="Validation warnings" value={String(summary?.pending_errors || 0)} detail="Rows needing review" tone={summary?.pending_errors ? "red" : "green"} />
          </div>

          <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
            <Panel title="Platform-wise contribution" subtitle="Taxable value and GST generated by each marketplace.">
              {platformData.length ? <div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={platformData}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Bar dataKey="taxable" fill="#1746A2" radius={[10, 10, 0, 0]} /><Bar dataKey="gst" fill="#F58220" radius={[10, 10, 0, 0]} /></BarChart></ResponsiveContainer></div> : <EmptyState title="No marketplace data yet" body="Upload marketplace files to populate platform charts." action={<Link className="rounded-2xl bg-[#1746A2] px-4 py-2 text-sm font-bold text-white" href="/marketplaces">Import files</Link>} />}
            </Panel>
            <Panel title="State-wise B2CS movement" subtitle="POS distribution used for GSTR-1 B2CS grouping.">
              {stateData.length ? <div className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={stateData}><defs><linearGradient id="gstState" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#0F9F6E" stopOpacity={0.35} /><stop offset="95%" stopColor="#0F9F6E" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Area type="monotone" dataKey="taxable" stroke="#0F9F6E" fill="url(#gstState)" strokeWidth={3} /></AreaChart></ResponsiveContainer></div> : <EmptyState title="No POS summary" body="State-wise charts appear after transactions are normalized." />}
            </Panel>
          </div>

          <div className="grid gap-6 xl:grid-cols-3">
            <Panel title="Recent imports" subtitle="Latest parser jobs and row counts.">
              <div className="space-y-3">
                {workspace.batches.slice(0, 5).map((batch) => <div key={batch.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3 dark:bg-white/5"><div><p className="font-bold capitalize">{batch.platform}</p><p className="text-xs text-slate-500">{batch.parsed_rows} rows / {batch.error_rows} errors</p></div><StatusPill status={batch.status} /></div>)}
                {!workspace.batches.length && <EmptyState title="No imports yet" body="Your import timeline will appear here." />}
              </div>
            </Panel>
            <Panel title="Validation warnings" subtitle="Critical row-level issues.">
              <div className="space-y-3">
                {warnings.slice(0, 4).map((row) => <div key={row.id} className="rounded-2xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700"><div className="flex gap-2 font-bold"><AlertTriangle className="size-4" />{row.invoice_no || row.order_id}</div><p className="mt-1 text-xs">{row.validation_errors || "Validation error"}</p></div>)}
                {!warnings.length && <div className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">No blocking validation errors.</div>}
              </div>
            </Panel>
            <Panel title="GSTR-1 readiness" subtitle="Export status and checklist.">
              <div className="space-y-3 text-sm">
                <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-3 dark:bg-white/5"><span>JSON status</span><StatusPill status={summary?.json_generation_status || "not_generated"} /></div>
                <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-3 dark:bg-white/5"><span>B2CS groups</span><b>{workspace.preview?.b2cs.length || 0}</b></div>
                <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-3 dark:bg-white/5"><span>SUPECO groups</span><b>{workspace.preview?.supeco?.supeco_det?.length || 0}</b></div>
                <Link href="/gstr1" className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#10244d] px-4 py-3 font-bold text-white"><FileJson className="size-4" /> Open GSTR-1 <ArrowUpRight className="size-4" /></Link>
              </div>
            </Panel>
          </div>
        </div>
      )}
    </AppShell>
  );
}
