// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/ai-auditor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/ai-auditor">> = Specific
  const handler = {} as typeof import("../../app/modules/ai-auditor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/gstr1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller/gstr1">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/gstr1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/manage-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller/manage-data">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/manage-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/marketplaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller/marketplaces">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/marketplaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller/profile">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/online-seller/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/online-seller/reports">> = Specific
  const handler = {} as typeof import("../../app/modules/online-seller/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/reconcile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/reconcile">> = Specific
  const handler = {} as typeof import("../../app/modules/reconcile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/reconcile/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/reconcile/reports">> = Specific
  const handler = {} as typeof import("../../app/modules/reconcile/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/reconcile/results/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/reconcile/results/[id]">> = Specific
  const handler = {} as typeof import("../../app/modules/reconcile/results/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/reconcile/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/reconcile/results">> = Specific
  const handler = {} as typeof import("../../app/modules/reconcile/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/reconcile/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/reconcile/upload">> = Specific
  const handler = {} as typeof import("../../app/modules/reconcile/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally/company">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally/export">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally/history">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally/import">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/mapping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally/mapping">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/mapping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/tally/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules/tally">> = Specific
  const handler = {} as typeof import("../../app/modules/tally/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/billing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/modules">> = Specific
  const handler = {} as typeof import("../../app/modules/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
